plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/cayman@v0.2.0
relative_links:
  enabled: true
  collections: true
include:
  - test.md
show_downloads: false
title: Anaglyph Day
description: Alles Gute ðŸ¥³
